'use client'
import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
  file_name,
  title,
  summaryText,
  createdAt,
}: {
  file_name: string;
  title: string;
  summaryText: string;
  createdAt: string;
}) {
    const handleDownload = () => {
  const summaryContent = `# ${title}
Generated Summary:
Generated on: ${new Date(createdAt).toLocaleDateString()}
    
${summaryText}
    
Original File: ${file_name}
generated by ClariDoc`;

  const blob = new Blob([summaryContent], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `Summary=${title.replace(/[^a-z0-9]/gi, "_")}.txt`;

  document.body.appendChild(link); // ✅ Add this
  link.click();
  document.body.removeChild(link); // ✅ Now safe

  URL.revokeObjectURL(url);
};

  return (
    <Button
      size={"sm"}
      className="h-8 px-3 bg-background text-rose-600 hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownload}
      variant={'ghost'}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
